#!/bin/sh

SSH_SERVER_PRIVATE_KEY="ssh-server/private.key"

if [ -f "$SSH_SERVER_PRIVATE_KEY" ]; then
    echo "$SSH_SERVER_PRIVATE_KEY already exists"
    read -p "Are you sure you want to overwrite it? " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
       exit 0
    fi
fi

openssl genrsa -out $SSH_SERVER_PRIVATE_KEY 4096
