#!/bin/sh

SSH_SERVER_PRIVATE_KEY="ssh-server/private.key"
API_SERVER_PRIVATE_KEY="api/private.key"

function generate_ssh_server_private_key {
    if [ -f "$SSH_SERVER_PRIVATE_KEY" ]; then
        echo "$SSH_SERVER_PRIVATE_KEY already exists"
        read -p "Are you sure you want to overwrite it? " -r
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            return
        fi
    fi

    openssl genrsa -out $SSH_SERVER_PRIVATE_KEY 4096
}

function generate_api_server_private_key {
    if [ -f "$API_SERVER_PRIVATE_KEY" ]; then
        echo "$API_SERVER_PRIVATE_KEY already exists"
        read -p "Are you sure you want to overwrite it? " -r
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            retrun
        fi
    fi

    openssl genrsa -out $API_SERVER_PRIVATE_KEY 4096
}

generate_ssh_server_private_key
generate_api_server_private_key
